### ISSUE TITLE
Should we be less specific?

### ISSUE THREAD

**Issue by ocefpaf** [rgaiacs/numfocus-2017-grant#5]
The text mentions training in Data Carpentry Lesson for Oceanography and I guess that is a niche thing.

Maybe we could say Data Carpentry Lesson for Earth Sciences? Most of the data problems faced by Meteorology, Oceanography, Geography, Geology, etc are quite similar.

The test also mentions to professor by named to justify the location (Florianópolis). Maybe we should not be that specific and mention that Florianópolis (and UFSC) is a thriving place for OSS and the location allows for participation of people  from South and Southeast (I am forcing it a little bit here :smile:).

I guess we should also mention the number of computing-related conferences that happened there to help make our point.

**Comment by rgaiacs** [comment]
> Maybe we could say Data Carpentry Lesson for Earth Sciences

I think this should be OK.

> The test also mentions to professor by named to justify the location (Florianópolis). Maybe we should not be that specific and mention that Florianópolis (and UFSC) is a thriving place for OSS and the location allows for participation of people from South and Southeast (I am forcing it a little bit here 😄).

This grant wouldn't allow us to test in other places. :-( I would love to fly some people to Salvador and Edinburgh. Those are the next grant we will write. :-) So I don't see the point of be less specific.

> I guess we should also mention the number of computing-related conferences that happened there to help make our point.

Are we going to interact with any of those events? If not I think is pointless to mention it since we only have two pages.

**Comment by ocefpaf** [comment]
> This grant wouldn't allow us to test in other places

I am not thinking about the grant. More on the reason for the chosen location.

> Are we going to interact with any of those events?

Same as above. I suggested mentioning them just to explain how Florianópolis is a thriving location for technology and all that jazz :wink:

If you have confidence we don't need that kind of info on the proposal I am OK with it.

**Comment by rgaiacs** [comment]
> More on the reason for the chosen location.

Mainly because @ocefpaf, @melissawm, and @juoceano are based in Florianópolis.

> I suggested mentioning them just to explain how Florianópolis is a thriving location for technology and all that jazz

I will try to add it.
